version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - environment

networks:
  environment:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"

volumes:
  pgdata:
